dataset_loader: 'OxfordEmbeddingPad'
data_dir: '/public/oxford_compressed/'
train_queries: 'training_queries_baseline.pickle'
test_queries: 'test_queries_baseline.pickle'
num_positives: 2
num_negatives: 2
batch_size: 4
num_worker: 16
get_negatives: False