dataset_loader: 'OxfordEmbeddingPad'
data_dir: '../data/oxford_compressed/'
train_queries: 'oxford_compressed/training_queries_baseline.pickle'
test_queries: 'oxford_compressed/test_queries_baseline.pickle'
num_positives: 1
num_negatives: 18
batch_size: 1
num_worker: 1
get_negatives: False